backend:
  name: github
  repo: gurt-overpeinzingen/ger-den-reijer

media_folder: "images"
public_folder: "/images"

collections:
  - name: "columns"
    label: "Columns"
    folder: "columns"
    create: true
    slug: "{{slug}}"
    extension: "html"

    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhoud", name: "body", widget: "markdown" }
